name: NexSkin
version: 0.0.1-beta
main: com.nexskin.NexSkin
api-version: '1.20'
author: NexLab
description: Скины без модов для пираток и лицензий
website: https://nex-skin.blockchain-core-group.com

commands:
  setskin:
    description: Установить скин
    usage: /setskin <url|ник>
    aliases: [skin, ss]
    permission: nexskin.use
    permission-message: §cНет прав!
  clearskin:
    description: Сбросить скин
    usage: /clearskin
    aliases: [cs]
    permission: nexskin.use
    permission-message: §cНет прав!
  updateskin:
    description: Обновить скин
    usage: /updateskin
    aliases: [us]
    permission: nexskin.use
    permission-message: §cНет прав!
  nexskin:
    description: Главная команда
    usage: /nexskin reload
    aliases: [ns]
    permission: nexskin.admin
    permission-message: §cНет прав!

permissions:
  nexskin.use:
    description: Использовать команды скинов (свой скин)
    default: true
  nexskin.admin:
    description: Админ-доступ (чужие скины, reload)
    default: op